MyOnlineShop.WebMVC/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyOnlineShop.WebMVC.Services.Catalog;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyOnlineShop.WebMVC.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly ICatalogService catalogService;

        public ProductsController(ICatalogService catalogService)
        {
            this.catalogService = catalogService;
        }

        public async Task<IActionResult> Index(int? currentPage = 1, string search = null)
        {
            try
            {
                var productPaginationViewModel = await this.catalogService.GetProductPagination(string.Empty, currentPage, search);

                return this.View(productPaginationViewModel);
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, "Internal server error.");
                }

                this.HandleException(apiEx);
            }

            return this.BadRequest();
        }

        public async Task<IActionResult> Details(int id, int? fromPage = 1)
        {
            try
            {
                var productDetailsViewModel = await this.catalogService.GetProductDetails(id, fromPage);

                return this.View(productDetailsViewModel);
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, "Internal server error.");
                }

                this.HandleException(apiEx);
            }

            return this.BadRequest();
        }

        private void HandleException(Exception ex)
        {
            ViewBag.CatalogInoperativeMsg = $"Catalog Service is inoperative {ex.GetType().Name} - {ex.Message}";
        }
    }
}

MyOnlineShop.WebMVC/Controllers/ShoppingCartsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyOnlineShop.Common.Constants;
using MyOnlineShop.Common.Services;
using MyOnlineShop.Common.ViewModels.Addresses;
using MyOnlineShop.Common.ViewModels.Products;
using MyOnlineShop.Common.ViewModels.ShoppingCarts;
using MyOnlineShop.WebMVC.Services.Catalog;
using MyOnlineShop.WebMVC.Services.Ordering;
using MyOnlineShop.WebMVC.Services.ShoppingCart;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyOnlineShop.WebMVC.Controllers
{
    [Authorize]
    public class ShoppingCartsController : Controller
    {
        private readonly IMapper mapper;
        private readonly IShoppingCartService shoppingCartService;
        private readonly ICatalogService catalogService;
        private readonly IOrderingService orderingService;
        private readonly ICurrentUserService currentUserService;
        private readonly IShoppingCartGatewayService shoppingCartGatewayService;

        public ShoppingCartsController(
            IMapper mapper,
            IShoppingCartService shoppingCartService,
            ICatalogService catalogService,
            IOrderingService orderingService,
            ICurrentUserService currentUserService,
            IShoppingCartGatewayService shoppingCartGatewayService)
        {
            this.mapper = mapper;
            this.shoppingCartService = shoppingCartService;
            this.catalogService = catalogService;
            this.orderingService = orderingService;
            this.currentUserService = currentUserService;
            this.shoppingCartGatewayService = shoppingCartGatewayService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var shoppingCartViewModel = await this.shoppingCartService.GetShoppingCart(this.currentUserService.UserId);

                return this.View(shoppingCartViewModel);
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, ErrorConstants.InternalServerErrorMessage);
                }

                this.HandleException(apiEx);
            }

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(int productId, int? fromPage = 1)
        {
            try
            {
                var productDetailsViewModel = await this.catalogService.GetProductDetails(productId, fromPage);

                var cartItemViewModel = this.mapper.Map<ProductDetailsViewModel, CartItemViewModel>(productDetailsViewModel);

                await this.shoppingCartService.AddToCart(this.currentUserService.UserId, cartItemViewModel);

                return this.Redirect($"/Products/Index/?currentPage={fromPage}");
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, ErrorConstants.InternalServerErrorMessage);
                }

                this.HandleException(apiEx);

                return this.Redirect($"/Products/Index/?currentPage={fromPage}");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Clear()
        {
            try
            {
                await this.shoppingCartService.Clear(this.currentUserService.UserId);

                return this.Redirect(nameof(Index));
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, ErrorConstants.InternalServerErrorMessage);
                }

                this.HandleException(apiEx);
            }

            return this.Redirect(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItem(int productId)
        {
            try
            {
                await this.shoppingCartService.RemoveItem(productId, this.currentUserService.UserId);

                return this.Redirect(nameof(Index));
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, ErrorConstants.InternalServerErrorMessage);
                }

                this.HandleException(apiEx);
            }

            return this.Redirect(nameof(Index));
        }

        public async Task<IActionResult> Checkout()
        {
            try
            {
                var shoppingCartOrderWrapperViewModel = await this.shoppingCartGatewayService.GetCheckout();

                return this.View(shoppingCartOrderWrapperViewModel);
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, ErrorConstants.InternalServerErrorMessage);
                }

                this.HandleException(apiEx);
            }

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderAddressViewModel orderAddressViewModel)
        {
            try
            {
                await this.shoppingCartGatewayService.Checkout(orderAddressViewModel);

                return this.RedirectToAction(nameof(Success));
            }
            catch (Refit.ApiException apiEx)
            {
                if (apiEx.HasContent)
                {
                    JsonConvert
                        .DeserializeObject<List<string>>(apiEx.Content)
                        .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, ErrorConstants.InternalServerErrorMessage);
                }

                this.HandleException(apiEx);
            }

            return this.View();
        }

        public IActionResult Success()
        {
            return this.View("Success", ShoppingCartConstants.SuccessMessage);
        }

        private void HandleException(Exception ex)
        {
            ViewBag.ShoppingCartInoperativeMsg = $"Shopping Cart Service is inoperative {ex.GetType().Name} - {ex.Message}";
        }
    }
}

MyOnlineShop.WebMVC/Views/Products/Details.cshtml
@model ProductDetailsViewModel

@{
    ViewData["Title"] = "Product Detail";
}

@if (!string.IsNullOrWhiteSpace(ViewBag.CatalogInoperativeMsg))
{
    <p class="text-white bg-danger">@ViewBag.CatalogInoperativeMsg</p>
}

<div class="row mb-2">
    <div class="col-md-4">
        <img src="@Model.ImageUrl" alt="Image" class="card-img">
    </div>
    <div class="col-md-8">
        <h5>@Model.Name</h5>
        <p>Price: $@Model.Price</p>
        <p>Stock Available: @Model.StockAvailable</p>
        <p>Weight in Kg: @Model.Weight</p>
        <p>Description: @Model.Description</p>
    </div>
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <div class="d-md-flex flex-md-row flex-md-wrap">
            <div class="product-image">
                <img src="@Model.ImageUrl" alt="Image" class="img-fluid" />
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <a asp-area="" asp-controller="Products" asp-action="Index" asp-route-currentPage="@Model.FromPageNumber" class="btn btn-secondary w-100">Back</a>
    </div>
    <div class="col-md-4 offset-md-2">
        <form method="post" asp-area="" asp-controller="ShoppingCarts" asp-action="AddProduct">
            <input type="hidden" name="ProductId" value="@Model.Id" />
            <input type="hidden" name="FromPage" value="@Model.FromPageNumber" />
            <button class="btn btn-primary w-100">Add to Trolley</button>
        </form>
    </div>
</div>

MyOnlineShop.WebMVC/Views/Products/Index.cshtml
@model ProductPaginationViewModel

@{
    ViewData["Title"] = "Manage Products";
}

@if (!string.IsNullOrWhiteSpace(ViewBag.CatalogInoperativeMsg))
{
    <p class="text-white bg-danger">@ViewBag.CatalogInoperativeMsg</p>
}

<div class="row mt-3 mb-3">
    <div class="col-md-7">
        <form method="get" asp-area="" asp-controller="Products" asp-action="Index" asp-route-search="@Model.PaginationViewModel.Search">
            <div class="form-row align-items-center">
                <div class="col-auto flex-grow-1 pr-0">
                    <input asp-for="Search" placeholder="What are you looking for?" class="form-control mb-2" />
                </div>
                <div class="col-auto align-self-md-end pl-0">
                    <button type="submit" class="btn btn-primary mb-2">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <h2 class="mb-3">Products</h2>
        @if (!Model.ProductIndexViewModels.Any())
        {
            <p class="bg-warning d-inline-block p-1">No products added yet.</p>
        }
        @for (int i = 0; i < Model.ProductIndexViewModels.Count; i += 4)
        {
            <div class="card-deck mt-2">
                @for (int k = 0; k <= 3 && k + i < Model.ProductIndexViewModels.Count(); k++)
                {
                    <div class="card p-0">
                        <a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@Model.ProductIndexViewModels[k + i].Id" asp-route-fromPage="@Model.PaginationViewModel.CurrentPage">
                            <div class="card-img-wrapper">
                                <img class="card-img-top" src="@Model.ProductIndexViewModels[k + i].ImageUrl" alt="Image">
                            </div>
                        </a>
                        <div class="card-body">
                            <a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@Model.ProductIndexViewModels[k + i].Id" asp-route-fromPage="@Model.PaginationViewModel.CurrentPage">
                                <h5 class="card-title">@Model.ProductIndexViewModels[k + i].Name</h5>
                                <p class="card-text">Description: @Model.ProductIndexViewModels[k + i].Description</p>
                                <p class="card-text">Price: $@Model.ProductIndexViewModels[k + i].Price</p>
                            </a>
                        </div>
                        <div class="card-footer text-center">
                            <form method="post" asp-area="" asp-controller="ShoppingCarts" asp-action="AddProduct">
                                <input type="hidden" name="ProductId" value="@Model.ProductIndexViewModels[k + i].Id" />
                                <input type="hidden" name="FromPage" value="@Model.PaginationViewModel.CurrentPage" />
                                <button class="btn btn-primary w-100">Add to Trolley</button>
                            </form>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</div>

<partial name="_PaginationPartial" model="Model.PaginationViewModel" />

MyOnlineShop.WebMVC/Views/Products/_PaginationPartial.cshtml
@model PaginationViewModel

<div class="text-center">
    <ul class="pagination justify-content-center">

        @if (Model.CurrentPage - 1 < 1)
        {
            <li class="page-item disabled">
                <a class="page-link" asp-area="" asp-controller="Products" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage - 1)" asp-route-search="@Model.Search" aria-label="Previous">
                    <span aria-hidden="true">Previous</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" asp-area="" asp-controller="Products" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage - 1)" asp-route-search="@Model.Search" aria-label="Previous">
                    <span aria-hidden="true">Previous</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        }

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            if (i == Model.CurrentPage)
            {
                <li class="page-item active">
                    <a class="page-link disabled">@i.ToString()</a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" asp-area="" asp-controller="Products" asp-action="Index" asp-route-currentPage="@i" asp-route-search="@Model.Search">@i.ToString()</a>
                </li>
            }
        }
        @if (Model.CurrentPage + 1 > Model.TotalPages)
        {
            <li class="page-item disabled">
                <a class="page-link" asp-area="" asp-controller="Products" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage + 1)" asp-route-search="@Model.Search" aria-label="Next">
                    <span aria-hidden="true">Next</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        }
        else
        {
            <li class="page-item">

                <a class="page-link" asp-area="" asp-controller="Products" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage + 1)" asp-route-search="@Model.Search" aria-label="Next">
                    <span aria-hidden="true">Next</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        }
    </ul>
</div>